./std < ./data/machinea0.in > ./data/machinea0.out
./std < ./data/machinea1.in > ./data/machinea1.out
./std < ./data/machinea2.in > ./data/machinea2.out
./std < ./data/machinea3.in > ./data/machinea3.out
./std < ./data/machinea4.in > ./data/machinea4.out
./std < ./data/machinea5.in > ./data/machinea5.out
./std < ./data/machinea6.in > ./data/machinea6.out
./std < ./data/machinea7.in > ./data/machinea7.out
./std < ./data/machinea8.in > ./data/machinea8.out
./std < ./data/machinea9.in > ./data/machinea9.out
