mv data/Flower1.out data/flower1.out 
mv data/Flower2.out data/flower2.out 
mv data/Flower3.out data/flower3.out 
mv data/Flower4.out data/flower4.out 
mv data/Flower5.out data/flower5.out 
mv data/Flower6.out data/flower6.out 
mv data/Flower7.out data/flower7.out 
mv data/Flower8.out data/flower8.out 
mv data/Flower9.out data/flower9.out 
mv data/Flower10.out data/flower10.out 
